### PR TITLE
Create PyPI package; few improvements

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Hi @willardmr, I made this to PyPI package `django-table-select-widget`. If you give me your username on PyPI I will give you rights to this repository.

### CODE REVIEW

**Comment by willardmr** [comment]
Hi @PetrDlouhy, these changes look great and I am happy to merge them in when you are done with the merge request (it looks like you are still adding to it).

If you want me to take over the PyPy I can but I will probably not be using this package much in the near future.  Would you be interested in taking over this github repository?

**Comment by PetrDlouhy** [comment]
@willardmr Thanks for responding. I am quite happy with the current state and I hope that I have done everything, that I wanted with releasing version `1.0.0`. I am not planing to touch the code any more unless I don't discover a bug or regression.

I think, that it might be the best if we share rights for both `GitHub` and `PyPI` (yes, PyPI has rights) repository, because it will decrease the chance, that the project will become abandoned without any chance of taking over by future maintainers.

One more thing: Do you have any licnece preference?

**Comment by willardmr** [comment]
That sounds good.  My pypy username is mrwillard and I just sent an invitation for you to become a collaborator on this project.

**Comment by PetrDlouhy** [comment]
OK, thanks. I have added you rights to the PyPI package. Following step would be to join this with `DjangoTableSelectWidget` so those two widgets would share as much code as possible. But I am not willing to give my time to that (I don't need that), so it waits for somebody with enough enthusiasm to do that.

**Comment by willardmr** [comment]
Sounds good.  I will take a look at it

**Pull request merged**
